name: Publish redque-clojure package to clojars

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: lein deps
      - name: Publish
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
          CLOJARS_PASS: ${{ secrets.CLOJARS_PASS }}
        run: lein deploy clojars
